#!/usr/bin/env bash
# Bash script to correct what is wrong with the server
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
pgrep nginx -o > /run/nginx.pid
nginx -s reload
echo '' > /run/nginx.pid
